# Generated by Django 4.2.1 on 2023-07-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_timestamp_productinteractions_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinteractions',
            name='isEmail',
            field=models.BooleanField(default=False),
        ),
    ]
