# Generated by Django 4.1 on 2023-10-01 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.action'),
        ),
        migrations.AlterField(
            model_name='product',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contract'),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.delivery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.measurement'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.origin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.payment'),
        ),
    ]
