# Generated by Django 4.2.1 on 2023-08-01 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinteractions',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.action'),
            preserve_default=False,
        ),
    ]
