# Generated by Django 4.2.1 on 2023-08-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_productinteractions_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinteractions',
            name='isWait',
            field=models.BooleanField(default=False),
        ),
    ]
