# Generated by Django 4.1 on 2023-10-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_product_action_alter_product_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promoteCompanyWebsite',
            field=models.BooleanField(default=False),
        ),
    ]
