# Generated by Django 4.2.1 on 2023-08-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productinteractions_iswait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinteractions',
            name='isWait',
            field=models.BooleanField(default=True),
        ),
    ]
