# Generated by Django 4.1 on 2023-10-15 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_creditspurchasing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditspurchasing',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
