# Generated by Django 4.1 on 2023-11-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_newsrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsrelease',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='static/news_release_media/'),
        ),
    ]
