# Generated by Django 4.2.1 on 2023-08-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_product_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinteractions',
            name='timestamp',
            field=models.BigIntegerField(),
        ),
    ]
