# Generated by Django 4.1 on 2023-08-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_productinteractions_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isArchived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='isExtended',
            field=models.BooleanField(default=False),
        ),
    ]
