# Generated by Django 4.1 on 2023-11-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_newsrelease_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsrelease',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
