# Generated by Django 4.1 on 2023-09-06 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_product_isexpired'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='openedOn',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
