# Generated by Django 4.1 on 2023-11-08 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_newsrelease_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsrelease',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
