# Generated by Django 4.1 on 2023-09-06 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_product_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='openedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
