# Generated by Django 4.1 on 2023-09-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_product_openedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='archivedOn',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
