# Generated by Django 4.1 on 2023-11-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_newsrelease_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditspurchasing',
            name='mode',
            field=models.CharField(choices=[('credit', 'Credit Purchased'), ('news', 'Published News Release')], default='credit', max_length=20),
        ),
    ]
