# Generated by Django 4.1 on 2023-10-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='credits',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
