# Generated by Django 4.2.1 on 2023-07-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customusers',
            managers=[
            ],
        ),
    ]
