# Generated by Django 4.2.1 on 2023-08-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customusers_isemailverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='emailToken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
