# Generated by Django 4.1 on 2023-09-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customusers_emailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
