# Generated by Django 4.1 on 2023-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customusers_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='is2FA',
            field=models.BooleanField(default=False),
        ),
    ]
