# Generated by Django 4.1 on 2023-09-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customusers_is2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='secret2FA',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
