# Generated by Django 4.1 on 2023-09-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customusers_secret2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='secret2FA',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
