# Generated by Django 4.1 on 2023-09-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customusers_secret2fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='lastLogin',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
