# Generated by Django 4.1 on 2023-09-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_customusers_lastlogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='lastLogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
