name: Django CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          # export npm to PATH env
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/Projects/stankevicius/
            git pull origin main
            source env/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            npx pm2 restart 0
            echo 'deployed successfully via ssh'
